# example netlify.toml
[build]
    command = "npm run build"
    functions = "api"
    publish = "dist"

[functions]
    directory = "api"

[[redirects]]
    from = "/api/*"
    to = ".netlify/functions/:splat"
    status = 200

[dev]
    #  port = 5000 # Port that the dev server will be listening on
    #  command = "yarn start" # Command to start your dev server
    #  publish = "dist" # Folder with the static content for _redirect file
