# example netlify.toml
[build]
    command = "npm run build"
    functions = "api"
    publish = "dist"

[functions]
    directory = "api"

[[redirects]]
    from = "/api/*"
    to = ".netlify/functions/:splat"
    status = 200

[dev]
	port = 3000
    command = "npm run vite" # Command to start your dev server
    #  publish = "dist" # Folder with the static content for _redirect file
